### ISSUE TITLE
请问 gf2-demo-cli 是用来做什么样的业务的呢

### ISSUE THREAD

**Issue by wozzup** [windvalley/gf2-demo#1]
`gf2-demo-api` 文档写的真好，点赞三连了！牛逼～

`gf2-demo-cli` 有点困惑大概都是用来实现哪些业务的呢？

**Comment by windvalley** [comment]
> `gf2-demo-api` 文档写的真好，点赞三连了！牛逼～
> 
> `gf2-demo-cli` 有点困惑大概都是用来实现哪些业务的呢？

一个项目可能并不只有webapi就能完美满足需求，比如需要独立的daemon程序用来消费webapi生成的任务队列，或者需要将webapi的能力通过命令行工具提供，或者需要其他的辅助类工具等等，此时就是cli的使用场景：）

**Comment by wozzup** [comment]
收到。感谢老师耐心解答。祝您工作顺利。
